services:
  personal_website:
    container_name: personal_website
    volumes:
      - ./apps:/apps
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - personal_website
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 